[Unit]
OnFailure=vps-sentry-unit-event@failed__%n.service

[Service]
ExecStartPost=-/bin/systemctl start --no-block vps-sentry-unit-event@started__%n.service
ExecStopPost=-/bin/systemctl start --no-block vps-sentry-unit-event@stopped__%n.service
